<div class="row">
	<div class="col-sm-4">
		<form class="block shadow" ng-submit="signIn()">
			<section class="section body">
				<h1>Sign In</h1>
				<div class="form-group">
					<label>
						Email Address
					</label>
					<input type="text" class="form-control input-lg" ng-model="user.email" required>
				</div>
				<div class="form-group">
					<label class="control-label">
						Password
					</label>
					<input type="password" class="form-control input-lg" ng-model="user.password" required>
				</div>
				<div class="checkbox">
					<label>
						<input type="checkbox" ng-model="user.remember">
						Remember me
					</label>
				</div>
				<div class="form-group text-right">
					<input type="submit" class="btn btn-lg btn-primary" value="Sign In">
				</div>
			</section>
		</form>
	</div>
</div>

